import { useState } from 'react';
import { CheckCircle2, FileSpreadsheet, RotateCcw } from 'lucide-react';
import Header from './components/Header'; import Footer from './components/Footer'; import LoginScreen from './components/LoginScreen'; import BatchScreen from './components/BatchScreen'; import CameraScreen from './components/CameraScreen'; import HistoryDrawer from './components/HistoryDrawer';
import { useAudioEffect } from './hooks/useAudioEffect'; import { useOfflineQueue } from './hooks/useOfflineQueue';
export default function App(){const [screen,setScreen]=useState('login'),[usuarioAtual,setUsuarioAtual]=useState(''),[listaChapas,setListaChapas]=useState([]),[drawer,setDrawer]=useState(false);const audio=useAudioEffect(),queue=useOfflineQueue();return <div className="app-shell"><div className="ambient-bg"/><Header historyCount={queue.coletas.length} onOpenHistory={()=>setDrawer(true)}/><main className="app-main">
{screen==='login'&&<LoginScreen playSound={audio} onLoginSuccess={u=>{setUsuarioAtual(u);setScreen('batch')}}/>}
{screen==='batch'&&<BatchScreen usuarioAtual={usuarioAtual} playSound={audio} onStartBatch={c=>{setListaChapas(c);setScreen('camera')}}/>}
{screen==='camera'&&<CameraScreen listaChapas={listaChapas} usuarioAtual={usuarioAtual} playSound={audio} onColetaRegistrada={queue.adicionarColeta} onFinish={()=>setScreen('complete')}/>} 
{screen==='complete'&&<section className="panel compact complete"><CheckCircle2 size={58}/><h2>Patrimônio Bens Móveis concluído</h2><p>Todos os bens do lote foram registrados.</p><button className="secondary-button" onClick={queue.exportarCSV}><FileSpreadsheet/> Baixar relatório CSV</button><button className="primary-button" onClick={()=>{setListaChapas([]);setScreen('batch')}}><RotateCcw/> Iniciar novo lote</button></section>}</main><Footer usuarioAtual={usuarioAtual}/><HistoryDrawer isOpen={drawer} onClose={()=>setDrawer(false)} coletas={queue.coletas} onExportCSV={queue.exportarCSV} onExportJSON={queue.exportarJSON} onClear={queue.limparHistorico}/></div>}
